### ISSUE TITLE
Craft 4 - Integrity Constraint Violation when re-saving an event

### ISSUE THREAD

**Issue by alexr8** [solspace/craft-calendar#136]
In Craft 4, creating an event in a calendar works fine - if i go back in to edit that event, i get an Integrity Constraint Violation when trying to save (which I didn't get in the same site in Craft 3).

**Steps to reproduce**

1. Create an event in Craft Calendar and save
2. Go back to the event and save again, the following error is thrown

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft 4.0.3
- Freeform Version: 4.0.0-beta.4
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade from Craft 3 to Craft 4

**Additional context**

`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'siteId' in field list is ambiguous in /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute()
#2 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal()
#3 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Query.php(330): yii\db\Command->queryAll()
#4 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/db/Query.php(214): yii\db\Query->column()
#5 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1476): craft\db\Query->column()
#6 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1508): craft\elements\db\ElementQuery->column()
#7 /home/forge/rwy.mutantlabs.com/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(493): craft\elements\db\ElementQuery->ids()
#8 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/services/Elements.php(2712): Solspace\Calendar\Elements\Db\EventQuery->all()
#9 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/services/Elements.php(766): craft\services\Elements->_saveElementInternal()
#10 /home/forge/rwy.mutantlabs.com/vendor/solspace/craft3-calendar/packages/plugin/src/Services/EventsService.php(207): craft\services\Elements->saveElement()
#11 /home/forge/rwy.mutantlabs.com/vendor/solspace/craft3-calendar/packages/plugin/src/Controllers/EventsController.php(248): Solspace\Calendar\Services\EventsService->saveEvent()
#12 [internal function]: Solspace\Calendar\Controllers\EventsController->actionSaveEvent()
#13 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#14 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#15 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#16 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction()
#17 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction()
#18 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest()
#19 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#20 /home/forge/rwy.mutantlabs.com/public/index.php(26): yii\base\Application->run()
#21 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'siteId' in field list is ambiguous
The SQL being executed was: SELECT `elements`.`id`, `siteId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `calendar_events` `calendar_events` ON `calendar_events`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
LEFT JOIN `drafts` `drafts` ON `drafts`.`id` = `elements`.`draftId`
LEFT JOIN `revisions` `revisions` ON `revisions`.`id` = `elements`.`revisionId`
INNER JOIN `calendar_calendars` ON `calendar_calendars`.`id` = calendar_events.`calendarId`
LEFT JOIN `users` ON `users`.`id` = calendar_events.`authorId`
WHERE (`elements_sites`.`siteId`=2) AND (`elements`.`id`=10851) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL)
ORDER BY `startDate`) `subquery`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `calendar_events` `calendar_events` ON `calendar_events`.`id` = `subquery`.`elementsId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `drafts` `drafts` ON `drafts`.`id` = `elements`.`draftId`
LEFT JOIN `revisions` `revisions` ON `revisions`.`id` = `elements`.`revisionId`
INNER JOIN `calendar_calendars` ON `calendar_calendars`.`id` = calendar_events.`calendarId`
LEFT JOIN `users` ON `users`.`id` = calendar_events.`authorId`
ORDER BY `startDate` in /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute()
#2 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal()
#3 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/db/Query.php(330): yii\db\Command->queryAll()
#4 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/db/Query.php(214): yii\db\Query->column()
#5 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1476): craft\db\Query->column()
#6 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1508): craft\elements\db\ElementQuery->column()
#7 /home/forge/rwy.mutantlabs.com/vendor/solspace/craft3-calendar/packages/plugin/src/Elements/Db/EventQuery.php(493): craft\elements\db\ElementQuery->ids()
#8 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/services/Elements.php(2712): Solspace\Calendar\Elements\Db\EventQuery->all()
#9 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/services/Elements.php(766): craft\services\Elements->_saveElementInternal()
#10 /home/forge/rwy.mutantlabs.com/vendor/solspace/craft3-calendar/packages/plugin/src/Services/EventsService.php(207): craft\services\Elements->saveElement()
#11 /home/forge/rwy.mutantlabs.com/vendor/solspace/craft3-calendar/packages/plugin/src/Controllers/EventsController.php(248): Solspace\Calendar\Services\EventsService->saveEvent()
#12 [internal function]: Solspace\Calendar\Controllers\EventsController->actionSaveEvent()
#13 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#14 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#15 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#16 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction()
#17 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction()
#18 /home/forge/rwy.mutantlabs.com/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest()
#19 /home/forge/rwy.mutantlabs.com/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#20 /home/forge/rwy.mutantlabs.com/public/index.php(26): yii\base\Application->run()
#21 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1052
    [2] => Column 'siteId' in field list is ambiguous
)
`

**Comment by kjmartens** [comment]
Sorry for the trouble @alexr8. I can duplicate this as well. We'll get a fix for it shortly.

**Comment by kjmartens** [comment]
This is fixed in v4.0.0-beta.5 now 🙂
