### ISSUE TITLE
Event sorting doesn't work when there are more than 100 events

### ISSUE THREAD

**Issue by mightyfineyall** [solspace/craft-calendar#138]
When sorting the admin/calendar/events page by post date, it pulls the first 100 created events and sorts them by post date. Then when page 2 of the event pagination is clicked, it sorts those by post date. So in this case, the 4 most recent events are on page 2. This results in the user needing to scroll to the bottom of the page and click the arrow every time in order to access and edit those four newest events. In other words, older events aren't getting shuffled to page 2 of the pagination.

**Steps to reproduce**

1. Have more than 100 events in Solspace Calendar
2. Click "Post Date"

**Expected behavior**
The newest events should be at the top, even when there are more than 100 events.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.44
- Calendar Version: 3.3.12
- Calendar Edition: Pro
- Fresh Install or Upgrade: Site was developed in 2019 and has been humming since.

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the trouble @mightyfineyall. Unfortunately this is a side effect of Calendar "going against the grain" of Craft. We made some decisions with Calendar earlier on to allow it to respect repeat rules where event data results become artificially inflated as well as avoid performance issues. In the future, we may be able to address the core issues causing things like this, but it would require a significant overhaul... so likely not in the near future unfortunately.
