### ISSUE TITLE
Delete occurrence of repeating event does not delete occurrence.

### ISSUE THREAD

**Issue by lukeholder** [solspace/craft-calendar#142]
**Describe the bug or issue you're experiencing**

**Steps to reproduce**

1. create a repeating event
2. delete occurrence
3. occurrence does not delete

- Craft Version: 4.0.4
- Calendar Version: 4.0.0-beta.5
- Calendar Edition: Pro Trial
- Fresh Install or Upgrade: Fresh Craft 4 site

**Additional context**

Tested in latest Firefox and Chrome

Video screencast of the issue: https://share.cleanshot.com/H2YDEN

Screenshot of repeating event setup:

![CleanShot 2022-06-18 at 00 11 58@2x](https://user-images.githubusercontent.com/133571/174336508-98be68f9-0838-47fa-a9f7-5025d67635c3.png)

Response from delete ajax request:

![CleanShot 2022-06-18 at 00 13 47@2x](https://user-images.githubusercontent.com/133571/174336894-66953240-8602-477b-b1dd-1f1570866ce4.png)

**Comment by lukeholder** [comment]
From a quick xdebug it looks like the exception service is returning the date as -1 day after this function:

https://github.com/solspace/craft-calendar/blob/master/packages/plugin/src/Services/ExceptionsService.php#L72

So the exceptions dates are off by a day.

**Comment by kjmartens** [comment]
Thanks @lukeholder. We're checking into it right now and noticed this as well... seems to do with timezones. In my timezone currently, this was working fine, but after adjusting my timezone to something different I can see the issue. We'll work on a fix. 🙂

**Comment by kjmartens** [comment]
This is now fixed in Calendar 3.13.13 and 4.0.0-beta.6. 🙂

**Comment by lukeholder** [comment]
Thanks @kjmartens !
