### ISSUE TITLE
Craft 4 - Calendar PRO - Cannot choose ICS Description/Location fields.

### ISSUE THREAD

**Issue by carterheron** [solspace/craft-calendar#146]
**Describe the bug or issue you're experiencing**
It seems I am unable to select from either the 'ICS Description Field' or the 'ICS Location Field' even though fields have been added to the event object.

<img width="1680" alt="calendarScreenshot" src="https://user-images.githubusercontent.com/58057403/176189317-2deaf9fa-f335-469a-9083-4c6654955146.png">

I checked a previous Craft 3 build where I am also using this plugin and I have no issues selecting the fields. I also tried installing on another instance of a Craft 4 (Upgrade this time instead of fresh install) and ran into the same issue where i could not select the fields.

**Steps to reproduce**
1. Setup new craft 4 build with the Calendar plugin installed
2. Create a few Plain Text fields and add them to the event object.
3. Save event object and then try to choose either 'ICS Description Field' or the 'ICS Location Field'.

**Expected behavior**
You should be able to choose from the fields that you add to the event object.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.0.5.2
- Calendar Version: 4.0.0-beta.5
- Calendar Edition: Pro
- Fresh Install or Upgrade: Install

**Additional context**

**Comment by kjmartens** [comment]
Hi @carterheron, sorry for the trouble. We'll get this fixed shortly. 🙂

**Comment by kjmartens** [comment]
This is now fixed in Calendar v4.0.0-beta.7 🙂
