### ISSUE TITLE
Handles should not contain -'s

### ISSUE THREAD

**Issue by khalwat** [solspace/craft-calendar#147]
This came up due to someone reporting this issue in SEOmatic: https://github.com/nystudio107/craft-seomatic/issues/1170

It looks like the handles in your [CalendarModel](https://github.com/solspace/craft-calendar/blob/master/packages/plugin/src/Models/CalendarModel.php#L30) allow characters that are not allowed in Craft handles, including `-`'s

Your `defineRules()` method doesn't return any validation rules for `handle`; you can use Craft's built-in `HandleValidator`if you like: https://github.com/craftcms/cms/blob/develop/src/validators/HandleValidator.php

It makes sure certain reserved words are not used, and also has the proper RegEx `[a-zA-Z][a-zA-Z0-9_]*` for what is allowed in a Craft handle.

**Comment by kjmartens** [comment]
Sorry for the delay @khalwat. Curious... I am able to create Craft Entries with handles/slugs of `my-test-entry`. Or am I missing something here? 🙂

**Comment by khalwat** [comment]
Those are slugs, and you can indeed have dashes in slugs.

**Comment by kjmartens** [comment]
Sorry, I am realizing you're referring to calendar name handles now. We'll check into that.

**Comment by kjmartens** [comment]
This is resolved now in Calendar 3.3.15 and 4.0.0-beta.8 🙂
