### ISSUE TITLE
Edit of multi-site event in slide-out saves the title from one site to all other sites

### ISSUE THREAD

**Issue by denisyilmaz** [solspace/craft-calendar#152]
We have a multi-site setup with two website groups:

- Group 1
    - English
    - German
- Group 2
    - English (disabled by default)
    - German (disabled by default)

**Steps to reproduce**

1. Create multi-site setup
2. Use "calendar event" field on some entry type
3. Link to a event
4. open event in slide-out
5. change title for one language

After saving, all sites / languages use the title from the edited language from the slide-out.
This behaviour is not happening when editing the event on the full edit page.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.48
- Calendar Version: 3.3.13.1

**Comment by kjmartens** [comment]
Sorry about this @denisyilmaz, and I apologize for the delay.

I can duplicate this issue in my testing and we'll look into a fix for it. 🙂

**Comment by kjmartens** [comment]
This has now been resolved in Calendar 4.0.4. Unfortunately we won't be able to support this change for Calendar 3.x
