### ISSUE TITLE
Ordering by endDate DESC does not return the latest event endDate

### ISSUE THREAD

**Issue by grcodemonkey** [solspace/craft-calendar#158]
**Describe the bug or issue you're experiencing**

Ordering by endDate DESC does not return the latest event endDate

**Steps to reproduce**

Use GraphQL interface to ORDER BY endDate in DESC order

```
query getLastestEventDate {
  solspace_calendar {
    latestStartDate: event(orderBy: "startDate DESC") {
      endDate
    }
    latestEndDate: event(orderBy: "endDate DESC") {
      endDate
    }
  }
}
```

![image](https://user-images.githubusercontent.com/1142219/184222899-c7f90e87-8dbb-424d-b23e-c0b920ba6aa2.png)

**Expected behavior**

The biggest endDate to be returned

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.43
- Calendar Version: 3.3.12
- Calendar Edition: Pro
- Fresh Install or Upgrade: Fresh Install

**Additional context**

**Comment by kjmartens** [comment]
This should now be fixed in v3.3.17+ and 4.0.0+. 🙂
