### ISSUE TITLE
Calendar > Events view is paginating incorrectly

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-calendar#172]
**Describe the bug or issue you're experiencing**

We have a site with 700+ calendar events. The title of each event is generated automatically based on the Entry it's related to. In the Events list view in the control panel, if I sort by Title alphabetically, it sorts it really weirdly. So on the first page, instead of getting all entries that start with A-D, then on page two the entries starting with D-G, for examepl - instead I have page one listing a bunch of entries from A-Z, then on page 2 a different set of entries with titles starting from A-Z

URL: http://sitename.test/admin/calendar/events/p2?site=english&source=*&sort=title-asc

Beginning of Page 1:

![image](https://user-images.githubusercontent.com/1250017/200515836-23e1d095-0831-457c-bf83-2887bcb4e004.png)

Beginning of page 2:

![image](https://user-images.githubusercontent.com/1250017/200516233-4e6278dc-17da-400c-ac3a-222ce229391f.png)

**Expected behavior**
Entries sorted by title should order all 700 entries and show me the first 100 in order, not just order a random selection of the 700

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.1
- Calendar Version: 4.0.0
- Calendar Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Sorry for the trouble @darylknight. I believe this might be a complication from Calendar using its own approach to account for recurrence rules and such. I'm not sure if there's an easy fix for this, but I've noted it and will have a developer investigate the issue soon. 🙂

**Comment by darylknight** [comment]
Got it - thanks!

**Comment by kjmartens** [comment]
This should be resolved in Calendar 4.0.3 now. Sorry for the wait. 🙂
