### ISSUE TITLE
{{ event.readableRepeatRule }} outputs the days in a weird order

### ISSUE THREAD

**Issue by darylknight** [solspace/craft-calendar#174]
**Describe the bug or issue you're experiencing**

When you set days for repetition rules, like in the below screenshot:

![image](https://user-images.githubusercontent.com/1250017/200522746-5652a00e-12f5-4087-8c4c-3477eff589f4.png)

then use event.readableRepeatRule on the front end, it shows the days in the order they were clicked in the control panel, rather than ordered by day of the week:

![image](https://user-images.githubusercontent.com/1250017/200522630-0e04527e-7e41-4424-8398-5c3b09138cc0.png)

This should instead say "Weekly on Monday, Tuesday, Wednesday, Thursday and Friday, starting from Sep 1, 2021, forever"

**Comment by kjmartens** [comment]
Thanks for reporting this @darylknight. I can duplicate this on my end as well.

**Comment by kjmartens** [comment]
This should be resolved in Calendar 4.0.2 now 🙂
