### ISSUE TITLE
Events view doesn't allow me to view/edit an element

### ISSUE THREAD

**Issue by belkin** [solspace/craft-calendar#181]
Events view doesn't allow me to view/edit an element but I'm able to create a new one. The events are editable via de Month/Week/Day views.

**Steps to reproduce**

1. Go to events view.
2. Try to edit event

**Expected behavior**
To able view or edit an event.

**Craft & Plugin Info:**

- Craft Version: 4.3.3
- Calendar Version: 4.0.0
- Calendar Edition: Pro
- Fresh Install or Upgrade: -

**Additional context**

![image](https://user-images.githubusercontent.com/3419659/202705094-2eb55469-84ba-4cfe-8c19-eb3c12ed86f8.png)

![image](https://user-images.githubusercontent.com/3419659/202705143-33ff1ee6-1a7a-44d7-aea3-810a82263077.png)

![image](https://user-images.githubusercontent.com/3419659/202706639-7d613ba5-6cb4-4c22-8e8c-f5eb1b5928b5.png)

**Comment by belkin** [comment]
With Craft 4.3.1 it works! Apparently it was something changed in Craft 4.3.2: 
https://github.com/craftcms/cms/commit/d7ad2a246356c79e749e86f4b1d7baafaa42f1fb

I don't know if this needs to be changed/fix in the plugin or Craft needs to fix it.

**Comment by kjmartens** [comment]
Thanks for the heads up @belkin. We'll check into this shortly.

**Comment by kjmartens** [comment]
This is fixed now in Calendar 4.0.1. 🙂
